### ISSUE TITLE
Add a submodule to support Bulk API 2.0

### ISSUE THREAD

**Issue by caffalaughrey** [forcedotcom/SalesforcePy#20]
## Background
[Bulk API support](https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/asynch_api_jobs_intro.htm) would be great.

## Suggested fix
Add `jobs` submodule.

**Comment by caffalaughrey** [comment]
Introduced in https://github.com/forcedotcom/SalesforcePy/pull/31.

**Comment by pepefloyd** [comment]
Niceeee!
