### ISSUE TITLE
Multiple OAuth flow support: User-Agent

### ISSUE THREAD

**Issue by caffalaughrey** [forcedotcom/SalesforcePy#21]
## Background
We should support the [User-Agent OAuth Flow](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_understanding_user_agent_oauth_flow.htm).

**Comment by demianbrecht** [comment]
@caffalaughrey I was thinking about this.. What were your thoughts on actually implementing it? Were you thinking simply taking in an access token assuming the user has already gone through the server redirect flow or end to end, which would be /incredibly/ complicated?

**Comment by caffalaughrey** [comment]
@pepefloyd remember when we discussed this way back when? Was the intention just to use the access token as @demianbrecht is suggesting here?

**Comment by pepefloyd** [comment]
@caffalaughrey I think the intention was to develop some sort of extension within this package for frameworks such as flask/django to authenticate but as @demianbrecht pointed out this is not a small task.

**Comment by adamlincoln** [comment]
I wrote an extension to requests-oauthlib for use with Salesforce:

https://github.com/SalesforceFoundation/salesforce-requests-oauthlib/blob/master/src/salesforce_requests_oauthlib/__init__.py

that supports a few different oauth flows.  Would it be helpful to merge my project with this one?

**Comment by caffalaughrey** [comment]
@adamlincoln ah so in your project, you're interacting with the client web browser directly correct? @pepefloyd I guess what you had in mind was lower-level. If we did develop an extension to facilitate this flow, what interfaces would it expose beyond something to instantiate a new client from an access token?

**Comment by caffalaughrey** [comment]
Closing this as for now there's no agreed approach on a generic flow implementation. As an alternative, I'm open to finding a way to create a client from an access token alone.

**Comment by tonimelismasalesforce** [comment]
Hey @caffalaughrey I guess the discussion above is all related to using web server flows or something similar where a user provides their credentials to a web app running SalesforcePy. What if I just tried creating a PR for a JWT bearer flow which would authenticate to Salesforce from SalesforcePy via a certificate, headless (server-to-server)?

**Comment by caffalaughrey** [comment]
@tonimelismasalesforce that sounds interesting for sure. For JWT as distinct from the User-Agent flow, I think a separate issue is warranted. Sure I'll keep my eyes peeled for a PR.
