### ISSUE TITLE
Execute Anonymous Has Unlinked Reference

### ISSUE THREAD

**Issue by antorcol** [forcedotcom/SalesforcePy#40]
In [Usage Examples](https://salesforcepy.readthedocs.io/en/latest/examples.html?highlight=anonymous), Execute Anonymous, it says 'see documentation for sample request body' - which docs?

**Comment by caffalaughrey** [comment]
Hey @antorcol I've just been through old commits and the [blame page](https://github.com/forcedotcom/SalesforcePy/blame/385aeedfb57d20c3bbd09c280e1223620a7da92e/README.md) for README.md prior to the documentation release and I can't figure out how this got there. Was this a section about [Approval Processes](https://github.com/forcedotcom/SalesforcePy/blob/385aeedfb57d20c3bbd09c280e1223620a7da92e/README.md#approval-process) that was partially removed during the switch to .rst files?

Assuming it was Approval Processes, I think the request body in question could be something like what's being assigned to the `body` variable in [this unit test](https://github.com/forcedotcom/SalesforcePy/blob/385aeedfb57d20c3bbd09c280e1223620a7da92e/tests/test_approvals.py#L38). And in case it's any additional use, the supported properties of this request body can be found in the official rest documentation [here](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_process_approvals.htm).

**Comment by tonimelisma** [comment]
Submitted a pull request for this issue https://github.com/forcedotcom/SalesforcePy/pull/47
