### ISSUE TITLE
README.md FAQ example on use of debug() contains invalid kwarg

### ISSUE THREAD

**Issue by caffalaughrey** [forcedotcom/SalesforcePy#8]
## Background
In the README.md file, under the section:
```markdown
### Is it possible to debug requests being made by `SalesforcePy`?
```

...there is a python example in which the `client.debug()` function is called.  In this example, a non-existing `debug` kwarg is passed:
```python
client.debug(debug=logging.INFO)    # Tell the client to debug at an info level
```

## Suggested fix
The expected kwarg is called `level`, so the example should be changed look like this:
```python
client.debug(level=logging.INFO)    # Tell the client to debug at an info level
```

**Comment by cormon1976** [comment]
@caffalaughrey I'll submit a fix for this 2moro :)

**Comment by caffalaughrey** [comment]
Fix in: https://github.com/forcedotcom/SalesforcePy/pull/14
