### ISSUE TITLE
setup.py url is wrong

### ISSUE THREAD

**Issue by caffalaughrey** [forcedotcom/SalesforcePy#9]
## Background
[The wrong `url` value is being passed when calling `setuptools.setup()`](https://github.com/forcedotcom/SalesforcePy/blob/9b9cd4d805c13051922ed1cd2866afd96e2daa5b/setup.py#L5) (The URL https://github.com/salesforce/SalesforcePy does not exist.)

## Suggested fix
Should be changed to this repo URL: https://github.com/forcedotcom/SalesforcePy.

**Comment by monotron** [comment]
I can pick this up :+1:

**Comment by caffalaughrey** [comment]
Moved fix to: https://github.com/forcedotcom/SalesforcePy/pull/14
